#include <stdio.h>
#include <assert.h>
#include <string.h>
#include <time.h>
#include <stdlib.h>
#include <math.h>

// === Forward Declarations ===
int factorial(int x);
int fibonacci(int n);
int add(int a, int b);
float pid_controller(float setpoint, float measurement, float kp, float ki, float kd);
float signal_generator(float frequency, float time);

// Unit tests for factorial from factorial.c
void test_factorial_factorial() {
    printf("\n=== Testing factorial from factorial.c ===\n");
    int passed = 0, total = 0;

    // Functional tests with known values
    printf("Test: factorial(5) == 120\n");
    assert(factorial(5) == 120);
    passed++; total++;

    printf("Test: factorial(0) == 1\n");
    assert(factorial(0) == 1);
    passed++; total++;

    printf("Test: factorial(1) == 1\n");
    assert(factorial(1) == 1);
    passed++; total++;

    printf("Function factorial: %d/%d tests passed\n", passed, total);
}

// Unit tests for fibonacci from factorial.c
void test_fibonacci_factorial() {
    printf("\n=== Testing fibonacci from factorial.c ===\n");
    int passed = 0, total = 0;

    // Fibonacci sequence tests
    printf("Test: fibonacci(0) == 0\n");
    assert(fibonacci(0) == 0);
    passed++; total++;

    printf("Test: fibonacci(1) == 1\n");
    assert(fibonacci(1) == 1);
    passed++; total++;

    printf("Test: fibonacci(5) == 5\n");
    assert(fibonacci(5) == 5);
    passed++; total++;

    printf("Function fibonacci: %d/%d tests passed\n", passed, total);
}

// Unit tests for add from factorial.c
void test_add_factorial() {
    printf("\n=== Testing add from factorial.c ===\n");
    int passed = 0, total = 0;

    // Functional Tests
    // Test add with valid integer a
    printf("TODO: Test add with valid integer a\n");
    // passed++; total++; // Uncomment when implemented

    // Test add with valid integer b
    printf("TODO: Test add with valid integer b\n");
    // passed++; total++; // Uncomment when implemented

    // Boundary Tests
    // Test add with a = 0
    printf("TODO: Test add with a = 0\n");
    // passed++; total++; // Uncomment when implemented

    // Test add with b = 0
    printf("TODO: Test add with b = 0\n");
    // passed++; total++; // Uncomment when implemented

    // Error Tests
    // Test add with negative a
    printf("TODO: Test add with negative a\n");
    // passed++; total++; // Uncomment when implemented

    // Test add with negative b
    printf("TODO: Test add with negative b\n");
    // passed++; total++; // Uncomment when implemented

    // Performance Tests
    printf("Function add: %d/%d tests passed\n", passed, total);
}

// Unit tests for pid_controller from pid_controller.c
void test_pid_controller_pid_controller() {
    printf("\n=== Testing pid_controller from pid_controller.c ===\n");
    int passed = 0, total = 0;

    // PID Controller tests
    printf("Test: PID basic control (setpoint=100, measurement=95)\n");
    float pid_result1 = pid_controller(100.0, 95.0, 0.1, 0.01, 0.05);
    printf("PID Output: %f\n", pid_result1);
    assert(pid_result1 != 0.0); // Should produce non-zero output
    passed++; total++;

    printf("Test: PID at setpoint (error=0)\n");
    float pid_result2 = pid_controller(50.0, 50.0, 1.0, 0.1, 0.1);
    printf("PID Output at setpoint: %f\n", pid_result2);
    // Note: may not be exactly 0 due to integral term
    passed++; total++;

    printf("Test: PID with negative error\n");
    float pid_result3 = pid_controller(0.0, 10.0, 0.5, 0.05, 0.02);
    printf("PID Output (negative error): %f\n", pid_result3);
    assert(pid_result3 < 0.0); // Should be negative for negative error
    passed++; total++;

    printf("Function pid_controller: %d/%d tests passed\n", passed, total);
}

// Unit tests for signal_generator from pid_controller.c
void test_signal_generator_pid_controller() {
    printf("\n=== Testing signal_generator from pid_controller.c ===\n");
    int passed = 0, total = 0;

    // Signal Generator tests
    printf("Test: Signal at time=0 should be 0\n");
    float sig1 = signal_generator(1.0, 0.0);
    printf("Signal(1.0, 0.0): %f\n", sig1);
    assert(sig1 >= -0.1 && sig1 <= 0.1); // Should be close to 0
    passed++; total++;

    printf("Test: Signal amplitude bounds [-1, 1]\n");
    float sig2 = signal_generator(2.0, 1.0);
    printf("Signal(2.0, 1.0): %f\n", sig2);
    assert(sig2 >= -1.1 && sig2 <= 1.1); // Should be within bounds
    passed++; total++;

    printf("Test: Signal frequency response\n");
    float sig3 = signal_generator(0.5, 2.0);
    printf("Signal(0.5, 2.0): %f\n", sig3);
    passed++; total++;

    printf("Function signal_generator: %d/%d tests passed\n", passed, total);
}

void run_all_tests() {
    printf("=== Enhanced C Function Test Runner ===\n");
    printf("Generated by NLP Test Generator\n");
    printf("Functions discovered: 5\n\n");

    test_factorial_factorial();
    test_fibonacci_factorial();
    test_add_factorial();
    test_pid_controller_pid_controller();
    test_signal_generator_pid_controller();

    printf("\n=== Test Summary Complete ===\n");
}

int main() {
    run_all_tests();
    return 0;
}